export const storeProducts = [
  {
    id: 1,

    title: "LOGO - Polo shirt",
    img: "img/product-1.png",
    price: 5000,
    company: "Hackett London",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Polo shirt",
    img: "img/product-2.png",
    price: 5000,
    company: "Denim Project",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "DANGERFIELD Polo shirt",
    img: "img/product-3.png",
    price: 5000,
    company: "Johnny Bigg",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: " Polo shirt",
    img: "img/product-4.png",
    price: 5000,
    company: "Jack & Jones",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "DANGERFIELD Polo shirt",
    img: "img/product-5.png",
    price: 5000,
    company: "Johnny Bigg",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "TIPPING SLIM Polo shirt",
    img: "img/product-6.png",
    price: 6000,
    company: "Calvin Klein Jeans",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "FLAMINGO - Polo shirt",
    img: "img/product-7.png",
    price: 6000,
    company: "Johnny Bigg",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Polo shirt",
    img: "img/product-8.png",
    price: 5000,
    company: "Tommy Jeans",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 2,
  title: "Go Explore Small 4 Wheel Hard Suitcase",
  img: "img/product-2.png",
  price: 16.99,
  company: "Go Explore ",
  info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  inCart: false,
  count: 0,
  total: 0,
};
